### requried
# this can be a company/brand or product namespace under which all content lives
namespace: goffinet
# the designation of this specific collection
name: install-gns3-server
# semantic versioning compliant version designation
version: 0.1
# a list of the collection's content authors: 'Full Name <email> (http://site) @nicks:irc/im/site#channel'
authors: Goffinet

### optional but strongly advised
# short summary of the collection
description: This Ansible collection include several roles to deploy GNS3 servers.
# a valid SPDX license identifier https://spdx.org/licenses/
license: CC-BY-SA-4.0
# list of keywords you want to associate the collection with for indexing/search systems
tags: gns3
# list of dependencies, other collections this collection requires to be installed for it to be usable
dependencies:

### urls
# url of originating SCM repository
repository:
# url to online docs
documentation:
# homepage of the collection/project
homepage:
# issue tracker url
issues:
