---

- include_tasks:
    file: install.yml
    apply:
      become: true

- include_tasks: configure.yml

- include_tasks: csr.yml

- include_tasks: sign.yml

- include_tasks: renew.yml

- include_tasks:
    file: revoke.yml
    apply:
      tags: easyrsa-revoke
  tags: easyrsa-revoke

- include_tasks: convert.yml

- include_tasks: dh.yml
  when: easyrsa_generate_dh | bool

- include_tasks: download.yml
  when:
    - easyrsa_download | length
      or easyrsa_download_pki | bool
