---

- name: Renew certificates
  command: easyrsa renew "{{ item.name }}"
  loop: "{{ easyrsa_renew }}"
  register: _result
  failed_when:
    - _result is failed
    - _result is not search('Certificate expires in more than 30 days')
  changed_when: _result is not failed
