---
- name: "BAREMETAL PROVISIONING"
  tags: [provision]
  hosts: all
  strategy: linear
  serial: 6
  gather_facts: False
  vars_files:
    - vars/secret.yml
  vars:
    ## Cloudflare DNS entries update
    #cloudflare_account_email: "mail@domain.com"
    #cloudflare_account_api_token: "XXXXX"
    ## Scaleway ID
    #scw_api_token: "XXXXX"
    #scw_organization: "XXXXX"
    ## Packet ID
    #packet_auth_token: "XXXXX"
  roles:
    - name: "Provider provisionning"
      role: "provision-servers"
